import * as s from "../../core/validation/index.js";
import type { Schema } from "../../core/validation/schema.js";

/**
 * Invoice number for this transaction. Automatically generated by Paddle when you mark a
 * transaction as `billed` where `collection_mode` is `manual`.
 */
export type InvoiceNumber = string;

export const invoiceNumberSchema: Schema<InvoiceNumber> = s.of<InvoiceNumber>(s.union([s.string()]));
