import * as s from "../core/validation/index.js";
import type { Schema } from "../core/validation/schema.js";

/** Represents a customer authentication token. */
export type CustomerAuthenticationToken = {
  /**
   * Authentication token generated by Paddle for this customer. Pass to Paddle.js when opening a
   * checkout to let customers work with saved payment methods.
   */
  customerAuthToken: string;
  /**
   * RFC 3339 datetime string of when this customer authentication token expires. The token is no
   * longer valid after this date.
   */
  expiresAt: Date;
};

export const customerAuthenticationTokenSchema: Schema<CustomerAuthenticationToken> =
  s.object<CustomerAuthenticationToken>({
    customerAuthToken: s.string(),
    expiresAt: s.dateTime(),
    _keysMap: {
      customerAuthToken: "customer_auth_token",
      expiresAt: "expires_at",
    },
  });
