import * as s from "../core/validation/index.js";
import type { Schema } from "../core/validation/schema.js";
import { billingDetails2Schema, type BillingDetails2 } from "./billing-details2.js";
import { collectionMode11Schema, type CollectionMode11 } from "./collection-mode11.js";
import { currencyCode65Schema, type CurrencyCode65 } from "./currency-code65.js";
import { publicTransactionOriginSchema, type PublicTransactionOrigin } from "./public-transaction-origin.js";
import { timePeriodSchema, type TimePeriod } from "./time-period.js";
import { transactionCheckoutSchema, type TransactionCheckout } from "./transaction-checkout.js";
import { transactionDetails1Schema, type TransactionDetails1 } from "./transaction-details1.js";
import { transactionItem1Schema, type TransactionItem1 } from "./transaction-item1.js";
import {
  transactionPaymentAttempt1Schema,
  type TransactionPaymentAttempt1,
} from "./transaction-payment-attempt1.js";
import { transactionStatusSchema, type TransactionStatus } from "./transaction-status.js";

/** New or changed entity. */
export type Data44 = {
  /** Unique Paddle ID for this transaction entity, prefixed with `txn_`. */
  id: string;
  /**
   * Status of this transaction. You may set a transaction to `billed` or `canceled`, other statuses
   * are set automatically by Paddle. Automatically-collected transactions may return `completed` if
   * payment is captured successfully, or `past_due` if payment failed.
   */
  status: TransactionStatus;
  /** Paddle ID of the customer that this transaction is for, prefixed with `ctm_`. */
  customerId: string | null;
  /** Paddle ID of the address that this transaction is for, prefixed with `add_`. */
  addressId: string | null;
  /** Paddle ID of the business that this transaction is for, prefixed with `biz_`. */
  businessId: string | null;
  /** Your own structured key-value data. */
  customData: Record<string, unknown> | null;
  /**
   * Supported three-letter ISO 4217 currency code. Must be `USD`, `EUR`, or `GBP` if
   * `collection_mode` is `manual`.
   */
  currencyCode: CurrencyCode65;
  /** Describes how this transaction was created. */
  origin: PublicTransactionOrigin;
  /** Paddle ID of the subscription that this transaction is for, prefixed with `sub_`. */
  subscriptionId: string | null;
  /**
   * Paddle ID of the invoice that this transaction is related to, prefixed with `inv_`. Used for
   * compatibility with the Paddle Invoice API, which is now deprecated. This field is scheduled to
   * be removed in the next version of the Paddle API.
   *
   * @deprecated
   */
  invoiceId: string | null;
  /**
   * Invoice number for this transaction. Automatically generated by Paddle when you mark a
   * transaction as `billed` where `collection_mode` is `manual`.
   */
  invoiceNumber: string | null;
  /**
   * How payment is collected for this transaction. `automatic` for checkout, `manual` for invoices.
   */
  collectionMode: CollectionMode11;
  /** Paddle ID of the discount applied to this transaction, prefixed with `dsc_`. */
  discountId: string | null;
  /** Details for invoicing. Required if `collection_mode` is `manual`. */
  billingDetails: BillingDetails2 | null;
  /**
   * Time period that this transaction is for. Set automatically by Paddle for subscription renewals
   * to describe the period that charges are for.
   */
  billingPeriod: TimePeriod | null;
  /** List of items on this transaction. For calculated totals, use `details.line_items`. */
  items: TransactionItem1[];
  /**
   * Calculated totals for a transaction, including proration, discounts, tax, and currency
   * conversion. Considered the source of truth for totals on a transaction.
   */
  details: TransactionDetails1;
  /**
   * List of payment attempts for this transaction, including successful payments. Sorted by
   * `created_at` in descending order, so most recent attempts are returned first.
   */
  payments: TransactionPaymentAttempt1[];
  /**
   * Paddle Checkout details for this transaction. Returned for automatically-collected transactions
   * and where `billing_details.enable_checkout` is `true` for manually-collected transactions;
   * `null` otherwise.
   */
  checkout: TransactionCheckout | null;
  /** RFC 3339 datetime string of when this entity was created. Set automatically by Paddle. */
  createdAt: Date;
  /** RFC 3339 datetime string of when this entity was updated. Set automatically by Paddle. */
  updatedAt: Date;
  /**
   * RFC 3339 datetime string of when this transaction was marked as `billed`. `null` for
   * transactions that aren't `billed` or `completed`. Set automatically by Paddle.
   */
  billedAt: Date | null;
  /**
   * RFC 3339 datetime string of when a transaction was revised. Revisions describe an update to
   * customer information for a billed or completed transaction. `null` if not revised. Set
   * automatically by Paddle.
   */
  revisedAt: Date | null;
};

export const data44Schema: Schema<Data44> = s.object<Data44>({
  id: s.string(),
  status: transactionStatusSchema,
  customerId: s.nullable(s.string()),
  addressId: s.nullable(s.string()),
  businessId: s.nullable(s.string()),
  customData: s.nullable(s.record(s.string(), s.unknown())),
  currencyCode: currencyCode65Schema,
  origin: publicTransactionOriginSchema,
  subscriptionId: s.nullable(s.string()),
  invoiceId: s.nullable(s.string()),
  invoiceNumber: s.nullable(s.string()),
  collectionMode: collectionMode11Schema,
  discountId: s.nullable(s.string()),
  billingDetails: s.nullable(s.lazy(() => billingDetails2Schema)),
  billingPeriod: s.nullable(s.lazy(() => timePeriodSchema)),
  items: s.array(s.lazy(() => transactionItem1Schema)),
  details: transactionDetails1Schema,
  payments: s.array(s.lazy(() => transactionPaymentAttempt1Schema)),
  checkout: s.nullable(s.lazy(() => transactionCheckoutSchema)),
  createdAt: s.dateTime(),
  updatedAt: s.dateTime(),
  billedAt: s.nullable(s.dateTime()),
  revisedAt: s.nullable(s.dateTime()),
  _keysMap: {
    customerId: "customer_id",
    addressId: "address_id",
    businessId: "business_id",
    customData: "custom_data",
    currencyCode: "currency_code",
    subscriptionId: "subscription_id",
    invoiceId: "invoice_id",
    invoiceNumber: "invoice_number",
    collectionMode: "collection_mode",
    discountId: "discount_id",
    billingDetails: "billing_details",
    billingPeriod: "billing_period",
    createdAt: "created_at",
    updatedAt: "updated_at",
    billedAt: "billed_at",
    revisedAt: "revised_at",
  },
});
