import * as s from "../core/validation/index.js";
import type { Schema } from "../core/validation/schema.js";
import { addressSchema, type Address } from "./address.js";
import { adjustmentTotals1Schema, type AdjustmentTotals1 } from "./adjustment-totals1.js";
import { adjustmentSchema, type Adjustment } from "./adjustment.js";
import { billingDetailsSchema, type BillingDetails } from "./billing-details.js";
import { businessSchema, type Business } from "./business.js";
import { CollectionMode, collectionModeSchema } from "./collection-mode.js";
import { currencyCodeSchema, type CurrencyCode } from "./currency-code.js";
import { customerSchema, type Customer } from "./customer.js";
import { discountSchema, type Discount } from "./discount.js";
import { paymentMethodType1Schema, type PaymentMethodType1 } from "./payment-method-type1.js";
import { publicTransactionOriginSchema, type PublicTransactionOrigin } from "./public-transaction-origin.js";
import { timePeriodSchema, type TimePeriod } from "./time-period.js";
import { transactionCheckoutSchema, type TransactionCheckout } from "./transaction-checkout.js";
import { transactionDetailsSchema, type TransactionDetails } from "./transaction-details.js";
import { transactionItemSchema, type TransactionItem } from "./transaction-item.js";
import {
  transactionPaymentAttemptSchema,
  type TransactionPaymentAttempt,
} from "./transaction-payment-attempt.js";
import { transactionStatusSchema, type TransactionStatus } from "./transaction-status.js";

export type SubscriptionTransactionWithIncludes = {
  id: string;
  /**
   * Status of this transaction. You may set a transaction to `billed` or `canceled`, other statuses
   * are set automatically by Paddle. Automatically-collected transactions may return `completed` if
   * payment is captured successfully, or `past_due` if payment failed.
   */
  status: TransactionStatus;
  /** Paddle ID of the customer that this transaction is for, prefixed with `ctm_`. */
  customerId?: string | null;
  /** Paddle ID of the address that this transaction is for, prefixed with `add_`. */
  addressId?: string | null;
  /** Paddle ID of the business that this transaction is for, prefixed with `biz_`. */
  businessId?: string | null;
  /** Your own structured key-value data. */
  customData?: Record<string, unknown> | null;
  /**
   * Supported three-letter ISO 4217 currency code. Must be `USD`, `EUR`, or `GBP` if
   * `collection_mode` is `manual`.
   */
  currencyCode: CurrencyCode;
  /** Describes how this transaction was created. */
  origin: PublicTransactionOrigin;
  /** Paddle ID of the subscription that this transaction is for, prefixed with `sub_`. */
  subscriptionId?: string | null;
  /**
   * Paddle ID of the invoice that this transaction is related to, prefixed with `inv_`. Used for
   * compatibility with the Paddle Invoice API, which is now deprecated. This field is scheduled to
   * be removed in the next version of the Paddle API.
   *
   * @deprecated
   */
  invoiceId?: string | null;
  /**
   * Invoice number for this transaction. Automatically generated by Paddle when you mark a
   * transaction as `billed` where `collection_mode` is `manual`.
   */
  invoiceNumber?: string | null;
  /**
   * How payment is collected for this transaction. `automatic` for checkout, `manual` for invoices.
   *
   * @default CollectionMode.Automatic
   */
  collectionMode?: CollectionMode;
  /** Paddle ID of the discount applied to this transaction, prefixed with `dsc_`. */
  discountId?: string | null;
  /** Details for invoicing. Required if `collection_mode` is `manual`. */
  billingDetails?: BillingDetails | null;
  /**
   * Time period that this transaction is for. Set automatically by Paddle for subscription renewals
   * to describe the period that charges are for.
   */
  billingPeriod?: TimePeriod | null;
  /** List of items on this transaction. For calculated totals, use `details.line_items`. */
  items: TransactionItem[];
  details: TransactionDetails;
  /**
   * List of payment attempts for this transaction, including successful payments. Sorted by
   * `created_at` in descending order, so most recent attempts are returned first.
   */
  payments: TransactionPaymentAttempt[];
  checkout?: TransactionCheckout | null;
  createdAt: Date;
  updatedAt: Date;
  /**
   * RFC 3339 datetime string of when this transaction was marked as `billed`. `null` for
   * transactions that aren't `billed` or `completed`. Set automatically by Paddle.
   */
  billedAt?: Date | null;
  /**
   * RFC 3339 datetime string of when a transaction was revised. Revisions describe an update to
   * customer information for a billed or completed transaction. `null` if not revised. Set
   * automatically by Paddle.
   */
  revisedAt?: Date | null;
  /**
   * Related customer for this transaction. Only returned if the API key has a Customers (Read)
   * permission.
   */
  customer?: Customer;
  /**
   * Related address for this transaction. Only returned if the API key has an Addresses (Read)
   * permission.
   */
  address?: Address;
  /**
   * Related business for this transaction. Only returned if a business exists for this transaction
   * and the API key has a Businesses (Read) permission.
   */
  business?: Business;
  /**
   * Related discount for this transaction. Only returned if a discount exists for this transaction
   * and the API key has a Discounts (Read) permission.
   */
  discount?: Discount;
  /**
   * Related adjustments for this transaction. Only returned if adjustments exist for this
   * transaction and the API key has an Adjustments (Read) permission.
   */
  adjustments?: Adjustment[];
  /**
   * Object containing totals for all adjustments on this transaction. Only returned if the API key
   * has an Adjustments (Read) permission.
   */
  adjustmentsTotals?: AdjustmentTotals1;
  /** List of payment methods available for this transaction. */
  availablePaymentMethods: PaymentMethodType1[];
};

export const subscriptionTransactionWithIncludesSchema: Schema<SubscriptionTransactionWithIncludes> =
  s.object<SubscriptionTransactionWithIncludes>({
    id: s.string(),
    status: transactionStatusSchema,
    customerId: s.optionalNullable(s.string()),
    addressId: s.optionalNullable(s.string()),
    businessId: s.optionalNullable(s.string()),
    customData: s.optionalNullable(s.record(s.string(), s.unknown())),
    currencyCode: currencyCodeSchema,
    origin: publicTransactionOriginSchema,
    subscriptionId: s.optionalNullable(s.string()),
    invoiceId: s.optionalNullable(s.string()),
    invoiceNumber: s.optionalNullable(s.string()),
    collectionMode: s.defaulted(collectionModeSchema, CollectionMode.Automatic),
    discountId: s.optionalNullable(s.string()),
    billingDetails: s.optionalNullable(s.lazy(() => billingDetailsSchema)),
    billingPeriod: s.optionalNullable(s.lazy(() => timePeriodSchema)),
    items: s.array(s.lazy(() => transactionItemSchema)),
    details: transactionDetailsSchema,
    payments: s.array(s.lazy(() => transactionPaymentAttemptSchema)),
    checkout: s.optionalNullable(s.lazy(() => transactionCheckoutSchema)),
    createdAt: s.dateTime(),
    updatedAt: s.dateTime(),
    billedAt: s.optionalNullable(s.dateTime()),
    revisedAt: s.optionalNullable(s.dateTime()),
    customer: s.optional(s.lazy(() => customerSchema)),
    address: s.optional(s.lazy(() => addressSchema)),
    business: s.optional(s.lazy(() => businessSchema)),
    discount: s.optional(s.lazy(() => discountSchema)),
    adjustments: s.optional(s.array(s.lazy(() => adjustmentSchema))),
    adjustmentsTotals: s.optional(s.lazy(() => adjustmentTotals1Schema)),
    availablePaymentMethods: s.array(s.lazy(() => paymentMethodType1Schema)),
    _keysMap: {
      customerId: "customer_id",
      addressId: "address_id",
      businessId: "business_id",
      customData: "custom_data",
      currencyCode: "currency_code",
      subscriptionId: "subscription_id",
      invoiceId: "invoice_id",
      invoiceNumber: "invoice_number",
      collectionMode: "collection_mode",
      discountId: "discount_id",
      billingDetails: "billing_details",
      billingPeriod: "billing_period",
      createdAt: "created_at",
      updatedAt: "updated_at",
      billedAt: "billed_at",
      revisedAt: "revised_at",
      adjustmentsTotals: "adjustments_totals",
      availablePaymentMethods: "available_payment_methods",
    },
  });
