import * as s from "../core/validation/index.js";
import type { Schema } from "../core/validation/schema.js";
import { collectionModeSchema, type CollectionMode } from "./collection-mode.js";
import { publicTransactionOriginSchema, type PublicTransactionOrigin } from "./public-transaction-origin.js";
import { transactionDetailsSchema, type TransactionDetails } from "./transaction-details.js";
import {
  transactionPaymentAttemptSchema,
  type TransactionPaymentAttempt,
} from "./transaction-payment-attempt.js";
import { transactionStatusSchema, type TransactionStatus } from "./transaction-status.js";
import { addressIdSchema, type AddressId } from "./unions/address-id.js";
import { billedAtSchema, type BilledAt } from "./unions/billed-at.js";
import { billingDetails25Schema, type BillingDetails25 } from "./unions/billing-details25.js";
import { billingPeriodSchema, type BillingPeriod } from "./unions/billing-period.js";
import { businessIdSchema, type BusinessId } from "./unions/business-id.js";
import { currencyCode17Schema, type CurrencyCode17 } from "./unions/currency-code17.js";
import { customDataSchema, type CustomData } from "./unions/custom-data.js";
import { customerIdSchema, type CustomerId } from "./unions/customer-id.js";
import { discountId9Schema, type DiscountId9 } from "./unions/discount-id9.js";
import { discount14Schema, type Discount14 } from "./unions/discount14.js";
import { invoiceIdSchema, type InvoiceId } from "./unions/invoice-id.js";
import { invoiceNumberSchema, type InvoiceNumber } from "./unions/invoice-number.js";
import { subscriptionId1Schema, type SubscriptionId1 } from "./unions/subscription-id1.js";
import { transactionCheckout1Schema, type TransactionCheckout1 } from "./unions/transaction-checkout1.js";
import { transactionItemUpdateSchema, type TransactionItemUpdate } from "./unions/transaction-item-update.js";

/** Represents a transaction entity when updating transactions. */
export type TransactionUpdate = {
  id?: string;
  /**
   * Status of this transaction. You may set a transaction to `billed` or `canceled`. Billed
   * transactions cannot be changed.
   *
   * For manually-collected transactions, marking as `billed` is essentially issuing an invoice.
   */
  status?: TransactionStatus;
  /** Paddle ID of the customer that this transaction is for, prefixed with `ctm_`. */
  customerId?: CustomerId;
  /** Paddle ID of the address that this transaction is for, prefixed with `add_`. */
  addressId?: AddressId;
  /** Paddle ID of the business that this transaction is for, prefixed with `biz_`. */
  businessId?: BusinessId;
  /** Your own structured key-value data. */
  customData?: CustomData;
  /**
   * Supported three-letter ISO 4217 currency code. Must be `USD`, `EUR`, or `GBP` if
   * `collection_mode` is `manual`.
   */
  currencyCode?: CurrencyCode17;
  origin?: PublicTransactionOrigin;
  /** Paddle ID of the subscription that this transaction is for, prefixed with `sub_`. */
  subscriptionId?: SubscriptionId1;
  /**
   * Paddle ID of the invoice that this transaction is related to, prefixed with `inv_`. Used for
   * compatibility with the Paddle Invoice API, which is now deprecated. This field is scheduled to
   * be removed in the next version of the Paddle API.
   *
   * @deprecated
   */
  invoiceId?: InvoiceId;
  /**
   * Invoice number for this transaction. Automatically generated by Paddle when you mark a
   * transaction as `billed` where `collection_mode` is `manual`.
   */
  invoiceNumber?: InvoiceNumber;
  /**
   * How payment is collected for this transaction. `automatic` for checkout, `manual` for invoices.
   */
  collectionMode?: CollectionMode;
  /** Paddle ID of the discount to apply to this transaction, prefixed with `dsc_`. */
  discountId?: DiscountId9;
  /** Apply a non-catalog discount to a transaction. Send one of `discount_id` or `discount`. */
  discount?: Discount14;
  /** Details for invoicing. Required if `collection_mode` is `manual`. */
  billingDetails?: BillingDetails25;
  /**
   * Time period that this transaction is for. Set automatically by Paddle for subscription renewals
   * to describe the period that charges are for.
   */
  billingPeriod?: BillingPeriod;
  /**
   * List of items on this transaction.
   *
   * When making a request, each object must contain either a `price_id` or a `price` object, and a
   * `quantity`.
   *
   * Include a `price_id` to charge for an existing catalog item, or a `price` object to charge for
   * a non-catalog item.
   */
  items?: TransactionItemUpdate[];
  details?: TransactionDetails;
  /**
   * List of payment attempts for this transaction, including successful payments. Sorted by
   * `created_at` in descending order, so most recent attempts are returned first.
   */
  payments?: TransactionPaymentAttempt[];
  /**
   * Paddle Checkout details for this transaction. You may pass a URL when creating or updating an
   * automatically-collected transaction, or when creating or updating a manually-collected
   * transaction where `billing_details.enable_checkout` is `true`.
   */
  checkout?: TransactionCheckout1;
  createdAt?: Date;
  updatedAt?: Date;
  /**
   * RFC 3339 datetime string of when this transaction was marked as `billed`. `null` for
   * transactions that aren't `billed` or `completed`. Set automatically by Paddle.
   */
  billedAt?: BilledAt;
};

export const transactionUpdateSchema: Schema<TransactionUpdate> = s.object<TransactionUpdate>({
  id: s.optional(s.string()),
  status: s.optional(s.lazy(() => transactionStatusSchema)),
  customerId: s.optional(s.lazy(() => customerIdSchema)),
  addressId: s.optional(s.lazy(() => addressIdSchema)),
  businessId: s.optional(s.lazy(() => businessIdSchema)),
  customData: s.optional(s.lazy(() => customDataSchema)),
  currencyCode: s.optional(s.lazy(() => currencyCode17Schema)),
  origin: s.optional(s.lazy(() => publicTransactionOriginSchema)),
  subscriptionId: s.optional(s.lazy(() => subscriptionId1Schema)),
  invoiceId: s.optional(s.lazy(() => invoiceIdSchema)),
  invoiceNumber: s.optional(s.lazy(() => invoiceNumberSchema)),
  collectionMode: s.optional(s.lazy(() => collectionModeSchema)),
  discountId: s.optional(s.lazy(() => discountId9Schema)),
  discount: s.optional(s.lazy(() => discount14Schema)),
  billingDetails: s.optional(s.lazy(() => billingDetails25Schema)),
  billingPeriod: s.optional(s.lazy(() => billingPeriodSchema)),
  items: s.optional(s.array(s.lazy(() => transactionItemUpdateSchema))),
  details: s.optional(s.lazy(() => transactionDetailsSchema)),
  payments: s.optional(s.array(s.lazy(() => transactionPaymentAttemptSchema))),
  checkout: s.optional(s.lazy(() => transactionCheckout1Schema)),
  createdAt: s.optional(s.dateTime()),
  updatedAt: s.optional(s.dateTime()),
  billedAt: s.optional(s.lazy(() => billedAtSchema)),
  _keysMap: {
    customerId: "customer_id",
    addressId: "address_id",
    businessId: "business_id",
    customData: "custom_data",
    currencyCode: "currency_code",
    subscriptionId: "subscription_id",
    invoiceId: "invoice_id",
    invoiceNumber: "invoice_number",
    collectionMode: "collection_mode",
    discountId: "discount_id",
    billingDetails: "billing_details",
    billingPeriod: "billing_period",
    createdAt: "created_at",
    updatedAt: "updated_at",
    billedAt: "billed_at",
  },
});
