import * as s from "../core/validation/index.js";
import type { Schema } from "../core/validation/schema.js";
import { CollectionMode, collectionModeSchema } from "./collection-mode.js";
import { currencyCodeSchema, type CurrencyCode } from "./currency-code.js";
import { publicTransactionOriginSchema, type PublicTransactionOrigin } from "./public-transaction-origin.js";
import { transactionDetailsSchema, type TransactionDetails } from "./transaction-details.js";
import { transactionItemSchema, type TransactionItem } from "./transaction-item.js";
import {
  transactionPaymentAttemptSchema,
  type TransactionPaymentAttempt,
} from "./transaction-payment-attempt.js";
import { transactionStatusSchema, type TransactionStatus } from "./transaction-status.js";
import { addressIdSchema, type AddressId } from "./unions/address-id.js";
import { billedAtSchema, type BilledAt } from "./unions/billed-at.js";
import { billingDetails1ModelSchema, type BillingDetails1Model } from "./unions/billing-details1-model.js";
import { billingPeriodSchema, type BillingPeriod } from "./unions/billing-period.js";
import { businessIdSchema, type BusinessId } from "./unions/business-id.js";
import { checkoutSchema, type Checkout } from "./unions/checkout.js";
import { customDataSchema, type CustomData } from "./unions/custom-data.js";
import { customerIdSchema, type CustomerId } from "./unions/customer-id.js";
import { discountIdSchema, type DiscountId } from "./unions/discount-id.js";
import { invoiceIdSchema, type InvoiceId } from "./unions/invoice-id.js";
import { invoiceNumberSchema, type InvoiceNumber } from "./unions/invoice-number.js";
import { revisedAtSchema, type RevisedAt } from "./unions/revised-at.js";
import { subscriptionId1Schema, type SubscriptionId1 } from "./unions/subscription-id1.js";

/** Represents a transaction entity. */
export type Transaction = {
  id: string;
  /**
   * Status of this transaction. You may set a transaction to `billed` or `canceled`, other statuses
   * are set automatically by Paddle. Automatically-collected transactions may return `completed` if
   * payment is captured successfully, or `past_due` if payment failed.
   */
  status: TransactionStatus;
  /** Paddle ID of the customer that this transaction is for, prefixed with `ctm_`. */
  customerId: CustomerId;
  /** Paddle ID of the address that this transaction is for, prefixed with `add_`. */
  addressId: AddressId;
  /** Paddle ID of the business that this transaction is for, prefixed with `biz_`. */
  businessId: BusinessId;
  /** Your own structured key-value data. */
  customData: CustomData;
  /**
   * Supported three-letter ISO 4217 currency code. Must be `USD`, `EUR`, or `GBP` if
   * `collection_mode` is `manual`.
   */
  currencyCode: CurrencyCode;
  /** Describes how this transaction was created. */
  origin: PublicTransactionOrigin;
  /** Paddle ID of the subscription that this transaction is for, prefixed with `sub_`. */
  subscriptionId: SubscriptionId1;
  /**
   * Paddle ID of the invoice that this transaction is related to, prefixed with `inv_`. Used for
   * compatibility with the Paddle Invoice API, which is now deprecated. This field is scheduled to
   * be removed in the next version of the Paddle API.
   *
   * @deprecated
   */
  invoiceId: InvoiceId;
  /**
   * Invoice number for this transaction. Automatically generated by Paddle when you mark a
   * transaction as `billed` where `collection_mode` is `manual`.
   */
  invoiceNumber: InvoiceNumber;
  /**
   * How payment is collected for this transaction. `automatic` for checkout, `manual` for invoices.
   *
   * @default CollectionMode.Automatic
   */
  collectionMode?: CollectionMode;
  /** Paddle ID of the discount applied to this transaction, prefixed with `dsc_`. */
  discountId: DiscountId;
  /** Details for invoicing. Required if `collection_mode` is `manual`. */
  billingDetails: BillingDetails1Model;
  /**
   * Time period that this transaction is for. Set automatically by Paddle for subscription renewals
   * to describe the period that charges are for.
   */
  billingPeriod: BillingPeriod;
  /** List of items on this transaction. For calculated totals, use `details.line_items`. */
  items: TransactionItem[];
  details: TransactionDetails;
  /**
   * List of payment attempts for this transaction, including successful payments. Sorted by
   * `created_at` in descending order, so most recent attempts are returned first.
   */
  payments: TransactionPaymentAttempt[];
  checkout: Checkout;
  createdAt: Date;
  updatedAt: Date;
  /**
   * RFC 3339 datetime string of when this transaction was marked as `billed`. `null` for
   * transactions that aren't `billed` or `completed`. Set automatically by Paddle.
   */
  billedAt: BilledAt;
  /**
   * RFC 3339 datetime string of when a transaction was revised. Revisions describe an update to
   * customer information for a billed or completed transaction. `null` if not revised. Set
   * automatically by Paddle.
   */
  revisedAt: RevisedAt;
};

export const transactionSchema: Schema<Transaction> = s.object<Transaction>({
  id: s.string(),
  status: transactionStatusSchema,
  customerId: customerIdSchema,
  addressId: addressIdSchema,
  businessId: businessIdSchema,
  customData: customDataSchema,
  currencyCode: currencyCodeSchema,
  origin: publicTransactionOriginSchema,
  subscriptionId: subscriptionId1Schema,
  invoiceId: invoiceIdSchema,
  invoiceNumber: invoiceNumberSchema,
  collectionMode: s.defaulted(collectionModeSchema, CollectionMode.Automatic),
  discountId: discountIdSchema,
  billingDetails: billingDetails1ModelSchema,
  billingPeriod: billingPeriodSchema,
  items: s.array(s.lazy(() => transactionItemSchema)),
  details: transactionDetailsSchema,
  payments: s.array(s.lazy(() => transactionPaymentAttemptSchema)),
  checkout: checkoutSchema,
  createdAt: s.dateTime(),
  updatedAt: s.dateTime(),
  billedAt: billedAtSchema,
  revisedAt: revisedAtSchema,
  _keysMap: {
    customerId: "customer_id",
    addressId: "address_id",
    businessId: "business_id",
    customData: "custom_data",
    currencyCode: "currency_code",
    subscriptionId: "subscription_id",
    invoiceId: "invoice_id",
    invoiceNumber: "invoice_number",
    collectionMode: "collection_mode",
    discountId: "discount_id",
    billingDetails: "billing_details",
    billingPeriod: "billing_period",
    createdAt: "created_at",
    updatedAt: "updated_at",
    billedAt: "billed_at",
    revisedAt: "revised_at",
  },
});
